### Health Check

GET http://localhost:3000/health HTTP/1.1

### Get user by ID

GET http://localhost:3000/users/1 HTTP/1.1

### Create a new user

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com"
}

### Update a user

PUT http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Alex Doe"
}

### Delete a user

DELETE http://localhost:3000/users/1 HTTP/1.1

### Get all users

GET http://localhost:3000/users HTTP/1.1